# SPDX-License-Identifier: PMPL-1.0-or-later

[workspace]
members = [
    "src/interfaces/graphql",
    "src/interfaces/grpc",
    "src/interfaces/rest",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
license = "PMPL-1.0-or-later"
